server:
  port: 8888
encrypt:
  key: AKFEABYXWRKLM
spring:
#never do this. this is unsecure
  security:
    user:
      name: sezayir
      password: test123 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sezayirdagtekin/spring-cloud-config
          search-paths:
          - station*
        encrypt:
          enabled: false